include:
  - "_config.yml"
  - "assets"
  - "common.js"
  - "common.js.map"
  - "index.html"
  - "main.js"
  - "main.js.map"
  - "node_modules_ionic_core_dist_esm_input-shims-61232da0_js.js"
  - "node_modules_ionic_core_dist_esm_input-shims-61232da0_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-accordion_2_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-accordion_2_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-action-sheet_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-action-sheet_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-alert_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-alert_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-app_8_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-app_8_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-avatar_3_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-avatar_3_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-back-button_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-back-button_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-backdrop_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-backdrop_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-breadcrumb_2_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-breadcrumb_2_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-button_2_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-button_2_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-card_5_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-card_5_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-checkbox_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-checkbox_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-chip_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-chip_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-col_3_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-col_3_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-datetime_3_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-datetime_3_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-fab_3_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-fab_3_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-img_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-img_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-infinite-scroll_2_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-infinite-scroll_2_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-input_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-input_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-item-option_3_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-item-option_3_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-item_8_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-item_8_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-loading_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-loading_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-menu_3_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-menu_3_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-modal_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-modal_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-nav_2_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-nav_2_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-picker-column-internal_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-picker-column-internal_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-picker-internal_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-picker-internal_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-popover_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-popover_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-progress-bar_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-progress-bar_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-radio_2_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-radio_2_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-range_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-range_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-refresher_2_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-refresher_2_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-reorder_2_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-reorder_2_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-ripple-effect_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-ripple-effect_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-route_4_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-route_4_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-searchbar_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-searchbar_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-segment_2_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-segment_2_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-select_3_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-select_3_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-slide_2_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-slide_2_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-spinner_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-spinner_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-split-pane_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-split-pane_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-tab-bar_2_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-tab-bar_2_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-tab_2_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-tab_2_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-text_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-text_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-textarea_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-textarea_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-toast_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-toast_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-toggle_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-toggle_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_ion-virtual-scroll_entry_js.js"
  - "node_modules_ionic_core_dist_esm_ion-virtual-scroll_entry_js.js.map"
  - "node_modules_ionic_core_dist_esm_status-tap-9af1ffca_js.js"
  - "node_modules_ionic_core_dist_esm_status-tap-9af1ffca_js.js.map"
  - "node_modules_ionic_core_dist_esm_swipe-back-b60369d0_js.js"
  - "node_modules_ionic_core_dist_esm_swipe-back-b60369d0_js.js.map"
  - "node_modules_ionic_core_dist_esm_swiper_bundle-28080340_js.js"
  - "node_modules_ionic_core_dist_esm_swiper_bundle-28080340_js.js.map"
  - "node_modules_ionic_core_dist_esm_tap-click-a895802b_js.js"
  - "node_modules_ionic_core_dist_esm_tap-click-a895802b_js.js.map"
  - "polyfills-core-js.js"
  - "polyfills-core-js.js.map"
  - "polyfills-dom.js"
  - "polyfills-dom.js.map"
  - "polyfills.js"
  - "polyfills.js.map"
  - "runtime.js"
  - "runtime.js.map"
  - "src_app_home_home_module_ts.js"
  - "src_app_home_home_module_ts.js.map"
  - "src_app_view-message_view-message_module_ts.js"
  - "src_app_view-message_view-message_module_ts.js.map"
  - "styles.css"
  - "styles.css.map"
  - "svg"
  - "vendor.js"
  - "vendor.js.map"
